apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: flux-system
  chart:
    spec:
      chart: hello-world
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: sdm4fzi
        namespace: flux-system
      interval: 1m
    values:
      image:
        tag: 20220505.1847  # {"$imagepolicy": "flux-system:hello-world:tag"}
