apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hello-world
  namespace: flux-system
spec:
  filterTags:
    pattern: '^v(?P<datetime>.*)$'
    extract: '$datetime'
  imageRepositoryRef:
    name: hello-world
    namespace: flux-system
  policy:
    numerical:
      order: asc
